### ISSUE TITLE
UX: limit the amount of time a new event can be active.

### ISSUE THREAD

**Issue by rosealexander** [rosealexander/app-jam#15]
Right now, someone could pick a page expiration date 100 years in the future. We should limit the amount of time a page can stay active to like 90 days or something like that. Take a look at the KeyboardDatePicker component in the CreatePage.js component

**Comment by autofakt** [comment]
I also noticed that it was allowing the user to select an end date from the past. Set the max campaign end date to 30 days into the future. This can easily be changed but I figured the less the time better so that the content remains fresh. Also because most events cant really wait that long.
